{
 "title": "Booking.API",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total{job=\"prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interval Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Connections RPM",
   "type": "stat",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "booking_api_created_database_context",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_httprequests_transactions_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Active Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_httprequests_active",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Updated Books",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "booking_api_updated_books", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deleted Books",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "booking_api_deleted_books", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Created Books",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "booking_api_created_books", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests Errors RPM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "application_httprequests_errors",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}